// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CommandData.proto

#ifndef PROTOBUF_CommandData_2eproto__INCLUDED
#define PROTOBUF_CommandData_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include "GenericValue.pb.h"
// @@protoc_insertion_point(includes)

namespace Octo {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_CommandData_2eproto();
void protobuf_AssignDesc_CommandData_2eproto();
void protobuf_ShutdownFile_CommandData_2eproto();

class CommandData;

// ===================================================================

class CommandData : public ::google::protobuf::MessageLite {
 public:
  CommandData();
  virtual ~CommandData();

  CommandData(const CommandData& from);

  inline CommandData& operator=(const CommandData& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_.GetNoArena(
        &::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }

  inline ::std::string* mutable_unknown_fields() {
    return _unknown_fields_.MutableNoArena(
        &::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }

  static const CommandData& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const CommandData* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(CommandData* other);

  // implements Message ----------------------------------------------

  inline CommandData* New() const { return New(NULL); }

  CommandData* New(::google::protobuf::Arena* arena) const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const CommandData& from);
  void MergeFrom(const CommandData& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(CommandData* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _arena_ptr_;
  }
  inline ::google::protobuf::Arena* MaybeArenaPtr() const {
    return _arena_ptr_;
  }
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 command_id = 1;
  bool has_command_id() const;
  void clear_command_id();
  static const int kCommandIdFieldNumber = 1;
  ::google::protobuf::int32 command_id() const;
  void set_command_id(::google::protobuf::int32 value);

  // optional .Octo.MapValue args = 2;
  bool has_args() const;
  void clear_args();
  static const int kArgsFieldNumber = 2;
  const ::Octo::MapValue& args() const;
  ::Octo::MapValue* mutable_args();
  ::Octo::MapValue* release_args();
  void set_allocated_args(::Octo::MapValue* args);

  // optional .Octo.MapValue result = 3;
  bool has_result() const;
  void clear_result();
  static const int kResultFieldNumber = 3;
  const ::Octo::MapValue& result() const;
  ::Octo::MapValue* mutable_result();
  ::Octo::MapValue* release_result();
  void set_allocated_result(::Octo::MapValue* result);

  // @@protoc_insertion_point(class_scope:Octo.CommandData)
 private:
  inline void set_has_command_id();
  inline void clear_has_command_id();
  inline void set_has_args();
  inline void clear_has_args();
  inline void set_has_result();
  inline void clear_has_result();

  ::google::protobuf::internal::ArenaStringPtr _unknown_fields_;
  ::google::protobuf::Arena* _arena_ptr_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::Octo::MapValue* args_;
  ::Octo::MapValue* result_;
  ::google::protobuf::int32 command_id_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_CommandData_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_CommandData_2eproto();
  #endif
  friend void protobuf_AssignDesc_CommandData_2eproto();
  friend void protobuf_ShutdownFile_CommandData_2eproto();

  void InitAsDefaultInstance();
  static CommandData* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// CommandData

// optional int32 command_id = 1;
inline bool CommandData::has_command_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CommandData::set_has_command_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CommandData::clear_has_command_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CommandData::clear_command_id() {
  command_id_ = 0;
  clear_has_command_id();
}
inline ::google::protobuf::int32 CommandData::command_id() const {
  // @@protoc_insertion_point(field_get:Octo.CommandData.command_id)
  return command_id_;
}
inline void CommandData::set_command_id(::google::protobuf::int32 value) {
  set_has_command_id();
  command_id_ = value;
  // @@protoc_insertion_point(field_set:Octo.CommandData.command_id)
}

// optional .Octo.MapValue args = 2;
inline bool CommandData::has_args() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CommandData::set_has_args() {
  _has_bits_[0] |= 0x00000002u;
}
inline void CommandData::clear_has_args() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void CommandData::clear_args() {
  if (args_ != NULL) args_->::Octo::MapValue::Clear();
  clear_has_args();
}
inline const ::Octo::MapValue& CommandData::args() const {
  // @@protoc_insertion_point(field_get:Octo.CommandData.args)
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  return args_ != NULL ? *args_ : *default_instance().args_;
#else
  return args_ != NULL ? *args_ : *default_instance_->args_;
#endif
}
inline ::Octo::MapValue* CommandData::mutable_args() {
  set_has_args();
  if (args_ == NULL) {
    args_ = new ::Octo::MapValue;
  }
  // @@protoc_insertion_point(field_mutable:Octo.CommandData.args)
  return args_;
}
inline ::Octo::MapValue* CommandData::release_args() {
  clear_has_args();
  ::Octo::MapValue* temp = args_;
  args_ = NULL;
  return temp;
}
inline void CommandData::set_allocated_args(::Octo::MapValue* args) {
  delete args_;
  args_ = args;
  if (args) {
    set_has_args();
  } else {
    clear_has_args();
  }
  // @@protoc_insertion_point(field_set_allocated:Octo.CommandData.args)
}

// optional .Octo.MapValue result = 3;
inline bool CommandData::has_result() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void CommandData::set_has_result() {
  _has_bits_[0] |= 0x00000004u;
}
inline void CommandData::clear_has_result() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void CommandData::clear_result() {
  if (result_ != NULL) result_->::Octo::MapValue::Clear();
  clear_has_result();
}
inline const ::Octo::MapValue& CommandData::result() const {
  // @@protoc_insertion_point(field_get:Octo.CommandData.result)
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  return result_ != NULL ? *result_ : *default_instance().result_;
#else
  return result_ != NULL ? *result_ : *default_instance_->result_;
#endif
}
inline ::Octo::MapValue* CommandData::mutable_result() {
  set_has_result();
  if (result_ == NULL) {
    result_ = new ::Octo::MapValue;
  }
  // @@protoc_insertion_point(field_mutable:Octo.CommandData.result)
  return result_;
}
inline ::Octo::MapValue* CommandData::release_result() {
  clear_has_result();
  ::Octo::MapValue* temp = result_;
  result_ = NULL;
  return temp;
}
inline void CommandData::set_allocated_result(::Octo::MapValue* result) {
  delete result_;
  result_ = result;
  if (result) {
    set_has_result();
  } else {
    clear_has_result();
  }
  // @@protoc_insertion_point(field_set_allocated:Octo.CommandData.result)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace Octo

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_CommandData_2eproto__INCLUDED
