// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GenericValue.proto

#ifndef PROTOBUF_GenericValue_2eproto__INCLUDED
#define PROTOBUF_GenericValue_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/map.h>
#include <google/protobuf/map_field_lite.h>
// @@protoc_insertion_point(includes)

namespace Octo {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_GenericValue_2eproto();
void protobuf_AssignDesc_GenericValue_2eproto();
void protobuf_ShutdownFile_GenericValue_2eproto();

class GenericValue;
class Int64ListValue;
class ListValue;
class MapValue;
class SMapValue;
class StringListValue;

// ===================================================================

class ListValue : public ::google::protobuf::MessageLite {
 public:
  ListValue();
  virtual ~ListValue();

  ListValue(const ListValue& from);

  inline ListValue& operator=(const ListValue& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_.GetNoArena(
        &::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }

  inline ::std::string* mutable_unknown_fields() {
    return _unknown_fields_.MutableNoArena(
        &::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }

  static const ListValue& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const ListValue* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(ListValue* other);

  // implements Message ----------------------------------------------

  inline ListValue* New() const { return New(NULL); }

  ListValue* New(::google::protobuf::Arena* arena) const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const ListValue& from);
  void MergeFrom(const ListValue& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ListValue* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _arena_ptr_;
  }
  inline ::google::protobuf::Arena* MaybeArenaPtr() const {
    return _arena_ptr_;
  }
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .Octo.GenericValue entries = 1;
  int entries_size() const;
  void clear_entries();
  static const int kEntriesFieldNumber = 1;
  const ::Octo::GenericValue& entries(int index) const;
  ::Octo::GenericValue* mutable_entries(int index);
  ::Octo::GenericValue* add_entries();
  ::google::protobuf::RepeatedPtrField< ::Octo::GenericValue >*
      mutable_entries();
  const ::google::protobuf::RepeatedPtrField< ::Octo::GenericValue >&
      entries() const;

  // @@protoc_insertion_point(class_scope:Octo.ListValue)
 private:

  ::google::protobuf::internal::ArenaStringPtr _unknown_fields_;
  ::google::protobuf::Arena* _arena_ptr_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::Octo::GenericValue > entries_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_GenericValue_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_GenericValue_2eproto();
  #endif
  friend void protobuf_AssignDesc_GenericValue_2eproto();
  friend void protobuf_ShutdownFile_GenericValue_2eproto();

  void InitAsDefaultInstance();
  static ListValue* default_instance_;
};
// -------------------------------------------------------------------

class Int64ListValue : public ::google::protobuf::MessageLite {
 public:
  Int64ListValue();
  virtual ~Int64ListValue();

  Int64ListValue(const Int64ListValue& from);

  inline Int64ListValue& operator=(const Int64ListValue& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_.GetNoArena(
        &::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }

  inline ::std::string* mutable_unknown_fields() {
    return _unknown_fields_.MutableNoArena(
        &::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }

  static const Int64ListValue& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const Int64ListValue* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(Int64ListValue* other);

  // implements Message ----------------------------------------------

  inline Int64ListValue* New() const { return New(NULL); }

  Int64ListValue* New(::google::protobuf::Arena* arena) const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const Int64ListValue& from);
  void MergeFrom(const Int64ListValue& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Int64ListValue* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _arena_ptr_;
  }
  inline ::google::protobuf::Arena* MaybeArenaPtr() const {
    return _arena_ptr_;
  }
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated sfixed64 entries = 1 [packed = true];
  int entries_size() const;
  void clear_entries();
  static const int kEntriesFieldNumber = 1;
  ::google::protobuf::int64 entries(int index) const;
  void set_entries(int index, ::google::protobuf::int64 value);
  void add_entries(::google::protobuf::int64 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
      entries() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
      mutable_entries();

  // @@protoc_insertion_point(class_scope:Octo.Int64ListValue)
 private:

  ::google::protobuf::internal::ArenaStringPtr _unknown_fields_;
  ::google::protobuf::Arena* _arena_ptr_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 > entries_;
  mutable int _entries_cached_byte_size_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_GenericValue_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_GenericValue_2eproto();
  #endif
  friend void protobuf_AssignDesc_GenericValue_2eproto();
  friend void protobuf_ShutdownFile_GenericValue_2eproto();

  void InitAsDefaultInstance();
  static Int64ListValue* default_instance_;
};
// -------------------------------------------------------------------

class StringListValue : public ::google::protobuf::MessageLite {
 public:
  StringListValue();
  virtual ~StringListValue();

  StringListValue(const StringListValue& from);

  inline StringListValue& operator=(const StringListValue& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_.GetNoArena(
        &::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }

  inline ::std::string* mutable_unknown_fields() {
    return _unknown_fields_.MutableNoArena(
        &::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }

  static const StringListValue& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const StringListValue* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(StringListValue* other);

  // implements Message ----------------------------------------------

  inline StringListValue* New() const { return New(NULL); }

  StringListValue* New(::google::protobuf::Arena* arena) const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const StringListValue& from);
  void MergeFrom(const StringListValue& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(StringListValue* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _arena_ptr_;
  }
  inline ::google::protobuf::Arena* MaybeArenaPtr() const {
    return _arena_ptr_;
  }
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated string entries = 1;
  int entries_size() const;
  void clear_entries();
  static const int kEntriesFieldNumber = 1;
  const ::std::string& entries(int index) const;
  ::std::string* mutable_entries(int index);
  void set_entries(int index, const ::std::string& value);
  void set_entries(int index, const char* value);
  void set_entries(int index, const char* value, size_t size);
  ::std::string* add_entries();
  void add_entries(const ::std::string& value);
  void add_entries(const char* value);
  void add_entries(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& entries() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_entries();

  // @@protoc_insertion_point(class_scope:Octo.StringListValue)
 private:

  ::google::protobuf::internal::ArenaStringPtr _unknown_fields_;
  ::google::protobuf::Arena* _arena_ptr_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::std::string> entries_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_GenericValue_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_GenericValue_2eproto();
  #endif
  friend void protobuf_AssignDesc_GenericValue_2eproto();
  friend void protobuf_ShutdownFile_GenericValue_2eproto();

  void InitAsDefaultInstance();
  static StringListValue* default_instance_;
};
// -------------------------------------------------------------------

class MapValue : public ::google::protobuf::MessageLite {
 public:
  MapValue();
  virtual ~MapValue();

  MapValue(const MapValue& from);

  inline MapValue& operator=(const MapValue& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_.GetNoArena(
        &::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }

  inline ::std::string* mutable_unknown_fields() {
    return _unknown_fields_.MutableNoArena(
        &::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }

  static const MapValue& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const MapValue* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(MapValue* other);

  // implements Message ----------------------------------------------

  inline MapValue* New() const { return New(NULL); }

  MapValue* New(::google::protobuf::Arena* arena) const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const MapValue& from);
  void MergeFrom(const MapValue& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(MapValue* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _arena_ptr_;
  }
  inline ::google::protobuf::Arena* MaybeArenaPtr() const {
    return _arena_ptr_;
  }
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  // map<fixed32, .Octo.GenericValue> entries = 1;
  int entries_size() const;
  void clear_entries();
  static const int kEntriesFieldNumber = 1;
  const ::google::protobuf::Map< ::google::protobuf::uint32, ::Octo::GenericValue >&
      entries() const;
  ::google::protobuf::Map< ::google::protobuf::uint32, ::Octo::GenericValue >*
      mutable_entries();

  // @@protoc_insertion_point(class_scope:Octo.MapValue)
 private:

  ::google::protobuf::internal::ArenaStringPtr _unknown_fields_;
  ::google::protobuf::Arena* _arena_ptr_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  typedef ::google::protobuf::internal::MapEntryLite<
      ::google::protobuf::uint32, ::Octo::GenericValue,
      ::google::protobuf::internal::WireFormatLite::TYPE_FIXED32,
      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
      0 >
      MapValue_EntriesEntry;
  ::google::protobuf::internal::MapFieldLite<
      ::google::protobuf::uint32, ::Octo::GenericValue,
      ::google::protobuf::internal::WireFormatLite::TYPE_FIXED32,
      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
      0 > entries_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_GenericValue_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_GenericValue_2eproto();
  #endif
  friend void protobuf_AssignDesc_GenericValue_2eproto();
  friend void protobuf_ShutdownFile_GenericValue_2eproto();

  void InitAsDefaultInstance();
  static MapValue* default_instance_;
};
// -------------------------------------------------------------------

class SMapValue : public ::google::protobuf::MessageLite {
 public:
  SMapValue();
  virtual ~SMapValue();

  SMapValue(const SMapValue& from);

  inline SMapValue& operator=(const SMapValue& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_.GetNoArena(
        &::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }

  inline ::std::string* mutable_unknown_fields() {
    return _unknown_fields_.MutableNoArena(
        &::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }

  static const SMapValue& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const SMapValue* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(SMapValue* other);

  // implements Message ----------------------------------------------

  inline SMapValue* New() const { return New(NULL); }

  SMapValue* New(::google::protobuf::Arena* arena) const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const SMapValue& from);
  void MergeFrom(const SMapValue& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(SMapValue* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _arena_ptr_;
  }
  inline ::google::protobuf::Arena* MaybeArenaPtr() const {
    return _arena_ptr_;
  }
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  // map<string, .Octo.GenericValue> entries = 1;
  int entries_size() const;
  void clear_entries();
  static const int kEntriesFieldNumber = 1;
  const ::google::protobuf::Map< ::std::string, ::Octo::GenericValue >&
      entries() const;
  ::google::protobuf::Map< ::std::string, ::Octo::GenericValue >*
      mutable_entries();

  // @@protoc_insertion_point(class_scope:Octo.SMapValue)
 private:

  ::google::protobuf::internal::ArenaStringPtr _unknown_fields_;
  ::google::protobuf::Arena* _arena_ptr_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  typedef ::google::protobuf::internal::MapEntryLite<
      ::std::string, ::Octo::GenericValue,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
      0 >
      SMapValue_EntriesEntry;
  ::google::protobuf::internal::MapFieldLite<
      ::std::string, ::Octo::GenericValue,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
      0 > entries_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_GenericValue_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_GenericValue_2eproto();
  #endif
  friend void protobuf_AssignDesc_GenericValue_2eproto();
  friend void protobuf_ShutdownFile_GenericValue_2eproto();

  void InitAsDefaultInstance();
  static SMapValue* default_instance_;
};
// -------------------------------------------------------------------

class GenericValue : public ::google::protobuf::MessageLite {
 public:
  GenericValue();
  virtual ~GenericValue();

  GenericValue(const GenericValue& from);

  inline GenericValue& operator=(const GenericValue& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_.GetNoArena(
        &::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }

  inline ::std::string* mutable_unknown_fields() {
    return _unknown_fields_.MutableNoArena(
        &::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }

  static const GenericValue& default_instance();

  enum ValueCase {
    kString = 1,
    kBytes = 2,
    kInt32 = 3,
    kInt64 = 5,
    kBoolean = 7,
    kReal = 8,
    kMap = 10,
    kStrMap = 11,
    kList = 12,
    kIntList = 13,
    kStrList = 14,
    VALUE_NOT_SET = 0,
  };

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const GenericValue* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(GenericValue* other);

  // implements Message ----------------------------------------------

  inline GenericValue* New() const { return New(NULL); }

  GenericValue* New(::google::protobuf::Arena* arena) const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const GenericValue& from);
  void MergeFrom(const GenericValue& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(GenericValue* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _arena_ptr_;
  }
  inline ::google::protobuf::Arena* MaybeArenaPtr() const {
    return _arena_ptr_;
  }
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string string = 1;
  bool has_string() const;
  void clear_string();
  static const int kStringFieldNumber = 1;
  const ::std::string& string() const;
  void set_string(const ::std::string& value);
  void set_string(const char* value);
  void set_string(const char* value, size_t size);
  ::std::string* mutable_string();
  ::std::string* release_string();
  void set_allocated_string(::std::string* string);

  // optional bytes bytes = 2;
  bool has_bytes() const;
  void clear_bytes();
  static const int kBytesFieldNumber = 2;
  const ::std::string& bytes() const;
  void set_bytes(const ::std::string& value);
  void set_bytes(const char* value);
  void set_bytes(const void* value, size_t size);
  ::std::string* mutable_bytes();
  ::std::string* release_bytes();
  void set_allocated_bytes(::std::string* bytes);

  // optional int32 int32 = 3;
  bool has_int32() const;
  void clear_int32();
  static const int kInt32FieldNumber = 3;
  ::google::protobuf::int32 int32() const;
  void set_int32(::google::protobuf::int32 value);

  // optional int64 int64 = 5;
  bool has_int64() const;
  void clear_int64();
  static const int kInt64FieldNumber = 5;
  ::google::protobuf::int64 int64() const;
  void set_int64(::google::protobuf::int64 value);

  // optional bool boolean = 7;
  bool has_boolean() const;
  void clear_boolean();
  static const int kBooleanFieldNumber = 7;
  bool boolean() const;
  void set_boolean(bool value);

  // optional double real = 8;
  bool has_real() const;
  void clear_real();
  static const int kRealFieldNumber = 8;
  double real() const;
  void set_real(double value);

  // optional .Octo.MapValue map = 10;
  bool has_map() const;
  void clear_map();
  static const int kMapFieldNumber = 10;
  const ::Octo::MapValue& map() const;
  ::Octo::MapValue* mutable_map();
  ::Octo::MapValue* release_map();
  void set_allocated_map(::Octo::MapValue* map);

  // optional .Octo.SMapValue str_map = 11;
  bool has_str_map() const;
  void clear_str_map();
  static const int kStrMapFieldNumber = 11;
  const ::Octo::SMapValue& str_map() const;
  ::Octo::SMapValue* mutable_str_map();
  ::Octo::SMapValue* release_str_map();
  void set_allocated_str_map(::Octo::SMapValue* str_map);

  // optional .Octo.ListValue list = 12;
  bool has_list() const;
  void clear_list();
  static const int kListFieldNumber = 12;
  const ::Octo::ListValue& list() const;
  ::Octo::ListValue* mutable_list();
  ::Octo::ListValue* release_list();
  void set_allocated_list(::Octo::ListValue* list);

  // optional .Octo.Int64ListValue int_list = 13;
  bool has_int_list() const;
  void clear_int_list();
  static const int kIntListFieldNumber = 13;
  const ::Octo::Int64ListValue& int_list() const;
  ::Octo::Int64ListValue* mutable_int_list();
  ::Octo::Int64ListValue* release_int_list();
  void set_allocated_int_list(::Octo::Int64ListValue* int_list);

  // optional .Octo.StringListValue str_list = 14;
  bool has_str_list() const;
  void clear_str_list();
  static const int kStrListFieldNumber = 14;
  const ::Octo::StringListValue& str_list() const;
  ::Octo::StringListValue* mutable_str_list();
  ::Octo::StringListValue* release_str_list();
  void set_allocated_str_list(::Octo::StringListValue* str_list);

  ValueCase value_case() const;
  // @@protoc_insertion_point(class_scope:Octo.GenericValue)
 private:
  inline void set_has_string();
  inline void set_has_bytes();
  inline void set_has_int32();
  inline void set_has_int64();
  inline void set_has_boolean();
  inline void set_has_real();
  inline void set_has_map();
  inline void set_has_str_map();
  inline void set_has_list();
  inline void set_has_int_list();
  inline void set_has_str_list();

  inline bool has_value() const;
  void clear_value();
  inline void clear_has_value();

  ::google::protobuf::internal::ArenaStringPtr _unknown_fields_;
  ::google::protobuf::Arena* _arena_ptr_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  union ValueUnion {
    ValueUnion() {}
    ::google::protobuf::internal::ArenaStringPtr string_;
    ::google::protobuf::internal::ArenaStringPtr bytes_;
    ::google::protobuf::int32 int32_;
    ::google::protobuf::int64 int64_;
    bool boolean_;
    double real_;
    ::Octo::MapValue* map_;
    ::Octo::SMapValue* str_map_;
    ::Octo::ListValue* list_;
    ::Octo::Int64ListValue* int_list_;
    ::Octo::StringListValue* str_list_;
  } value_;
  ::google::protobuf::uint32 _oneof_case_[1];

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_GenericValue_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_GenericValue_2eproto();
  #endif
  friend void protobuf_AssignDesc_GenericValue_2eproto();
  friend void protobuf_ShutdownFile_GenericValue_2eproto();

  void InitAsDefaultInstance();
  static GenericValue* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// ListValue

// repeated .Octo.GenericValue entries = 1;
inline int ListValue::entries_size() const {
  return entries_.size();
}
inline void ListValue::clear_entries() {
  entries_.Clear();
}
inline const ::Octo::GenericValue& ListValue::entries(int index) const {
  // @@protoc_insertion_point(field_get:Octo.ListValue.entries)
  return entries_.Get(index);
}
inline ::Octo::GenericValue* ListValue::mutable_entries(int index) {
  // @@protoc_insertion_point(field_mutable:Octo.ListValue.entries)
  return entries_.Mutable(index);
}
inline ::Octo::GenericValue* ListValue::add_entries() {
  // @@protoc_insertion_point(field_add:Octo.ListValue.entries)
  return entries_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::Octo::GenericValue >*
ListValue::mutable_entries() {
  // @@protoc_insertion_point(field_mutable_list:Octo.ListValue.entries)
  return &entries_;
}
inline const ::google::protobuf::RepeatedPtrField< ::Octo::GenericValue >&
ListValue::entries() const {
  // @@protoc_insertion_point(field_list:Octo.ListValue.entries)
  return entries_;
}

// -------------------------------------------------------------------

// Int64ListValue

// repeated sfixed64 entries = 1 [packed = true];
inline int Int64ListValue::entries_size() const {
  return entries_.size();
}
inline void Int64ListValue::clear_entries() {
  entries_.Clear();
}
inline ::google::protobuf::int64 Int64ListValue::entries(int index) const {
  // @@protoc_insertion_point(field_get:Octo.Int64ListValue.entries)
  return entries_.Get(index);
}
inline void Int64ListValue::set_entries(int index, ::google::protobuf::int64 value) {
  entries_.Set(index, value);
  // @@protoc_insertion_point(field_set:Octo.Int64ListValue.entries)
}
inline void Int64ListValue::add_entries(::google::protobuf::int64 value) {
  entries_.Add(value);
  // @@protoc_insertion_point(field_add:Octo.Int64ListValue.entries)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
Int64ListValue::entries() const {
  // @@protoc_insertion_point(field_list:Octo.Int64ListValue.entries)
  return entries_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
Int64ListValue::mutable_entries() {
  // @@protoc_insertion_point(field_mutable_list:Octo.Int64ListValue.entries)
  return &entries_;
}

// -------------------------------------------------------------------

// StringListValue

// repeated string entries = 1;
inline int StringListValue::entries_size() const {
  return entries_.size();
}
inline void StringListValue::clear_entries() {
  entries_.Clear();
}
inline const ::std::string& StringListValue::entries(int index) const {
  // @@protoc_insertion_point(field_get:Octo.StringListValue.entries)
  return entries_.Get(index);
}
inline ::std::string* StringListValue::mutable_entries(int index) {
  // @@protoc_insertion_point(field_mutable:Octo.StringListValue.entries)
  return entries_.Mutable(index);
}
inline void StringListValue::set_entries(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:Octo.StringListValue.entries)
  entries_.Mutable(index)->assign(value);
}
inline void StringListValue::set_entries(int index, const char* value) {
  entries_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:Octo.StringListValue.entries)
}
inline void StringListValue::set_entries(int index, const char* value, size_t size) {
  entries_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:Octo.StringListValue.entries)
}
inline ::std::string* StringListValue::add_entries() {
  return entries_.Add();
}
inline void StringListValue::add_entries(const ::std::string& value) {
  entries_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:Octo.StringListValue.entries)
}
inline void StringListValue::add_entries(const char* value) {
  entries_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:Octo.StringListValue.entries)
}
inline void StringListValue::add_entries(const char* value, size_t size) {
  entries_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:Octo.StringListValue.entries)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
StringListValue::entries() const {
  // @@protoc_insertion_point(field_list:Octo.StringListValue.entries)
  return entries_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
StringListValue::mutable_entries() {
  // @@protoc_insertion_point(field_mutable_list:Octo.StringListValue.entries)
  return &entries_;
}

// -------------------------------------------------------------------

// MapValue

// map<fixed32, .Octo.GenericValue> entries = 1;
inline int MapValue::entries_size() const {
  return entries_.size();
}
inline void MapValue::clear_entries() {
  entries_.Clear();
}
inline const ::google::protobuf::Map< ::google::protobuf::uint32, ::Octo::GenericValue >&
MapValue::entries() const {
  // @@protoc_insertion_point(field_map:Octo.MapValue.entries)
  return entries_.GetMap();
}
inline ::google::protobuf::Map< ::google::protobuf::uint32, ::Octo::GenericValue >*
MapValue::mutable_entries() {
  // @@protoc_insertion_point(field_mutable_map:Octo.MapValue.entries)
  return entries_.MutableMap();
}

// -------------------------------------------------------------------

// SMapValue

// map<string, .Octo.GenericValue> entries = 1;
inline int SMapValue::entries_size() const {
  return entries_.size();
}
inline void SMapValue::clear_entries() {
  entries_.Clear();
}
inline const ::google::protobuf::Map< ::std::string, ::Octo::GenericValue >&
SMapValue::entries() const {
  // @@protoc_insertion_point(field_map:Octo.SMapValue.entries)
  return entries_.GetMap();
}
inline ::google::protobuf::Map< ::std::string, ::Octo::GenericValue >*
SMapValue::mutable_entries() {
  // @@protoc_insertion_point(field_mutable_map:Octo.SMapValue.entries)
  return entries_.MutableMap();
}

// -------------------------------------------------------------------

// GenericValue

// optional string string = 1;
inline bool GenericValue::has_string() const {
  return value_case() == kString;
}
inline void GenericValue::set_has_string() {
  _oneof_case_[0] = kString;
}
inline void GenericValue::clear_string() {
  if (has_string()) {
    value_.string_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    clear_has_value();
  }
}
inline const ::std::string& GenericValue::string() const {
  // @@protoc_insertion_point(field_get:Octo.GenericValue.string)
  if (has_string()) {
    return value_.string_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  return *&::google::protobuf::internal::GetEmptyStringAlreadyInited();
}
inline void GenericValue::set_string(const ::std::string& value) {
  // @@protoc_insertion_point(field_set:Octo.GenericValue.string)
  if (!has_string()) {
    clear_value();
    set_has_string();
    value_.string_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  value_.string_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Octo.GenericValue.string)
}
inline void GenericValue::set_string(const char* value) {
  if (!has_string()) {
    clear_value();
    set_has_string();
    value_.string_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  value_.string_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Octo.GenericValue.string)
}
inline void GenericValue::set_string(const char* value, size_t size) {
  if (!has_string()) {
    clear_value();
    set_has_string();
    value_.string_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  value_.string_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Octo.GenericValue.string)
}
inline ::std::string* GenericValue::mutable_string() {
  if (!has_string()) {
    clear_value();
    set_has_string();
    value_.string_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_mutable:Octo.GenericValue.string)
  return value_.string_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GenericValue::release_string() {
  if (has_string()) {
    clear_has_value();
    return value_.string_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  } else {
    return NULL;
  }
}
inline void GenericValue::set_allocated_string(::std::string* string) {
  if (!has_string()) {
    value_.string_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  clear_value();
  if (string != NULL) {
    set_has_string();
    value_.string_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
        string);
  }
  // @@protoc_insertion_point(field_set_allocated:Octo.GenericValue.string)
}

// optional bytes bytes = 2;
inline bool GenericValue::has_bytes() const {
  return value_case() == kBytes;
}
inline void GenericValue::set_has_bytes() {
  _oneof_case_[0] = kBytes;
}
inline void GenericValue::clear_bytes() {
  if (has_bytes()) {
    value_.bytes_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    clear_has_value();
  }
}
inline const ::std::string& GenericValue::bytes() const {
  // @@protoc_insertion_point(field_get:Octo.GenericValue.bytes)
  if (has_bytes()) {
    return value_.bytes_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  return *&::google::protobuf::internal::GetEmptyStringAlreadyInited();
}
inline void GenericValue::set_bytes(const ::std::string& value) {
  // @@protoc_insertion_point(field_set:Octo.GenericValue.bytes)
  if (!has_bytes()) {
    clear_value();
    set_has_bytes();
    value_.bytes_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  value_.bytes_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Octo.GenericValue.bytes)
}
inline void GenericValue::set_bytes(const char* value) {
  if (!has_bytes()) {
    clear_value();
    set_has_bytes();
    value_.bytes_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  value_.bytes_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Octo.GenericValue.bytes)
}
inline void GenericValue::set_bytes(const void* value, size_t size) {
  if (!has_bytes()) {
    clear_value();
    set_has_bytes();
    value_.bytes_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  value_.bytes_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Octo.GenericValue.bytes)
}
inline ::std::string* GenericValue::mutable_bytes() {
  if (!has_bytes()) {
    clear_value();
    set_has_bytes();
    value_.bytes_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_mutable:Octo.GenericValue.bytes)
  return value_.bytes_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GenericValue::release_bytes() {
  if (has_bytes()) {
    clear_has_value();
    return value_.bytes_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  } else {
    return NULL;
  }
}
inline void GenericValue::set_allocated_bytes(::std::string* bytes) {
  if (!has_bytes()) {
    value_.bytes_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  clear_value();
  if (bytes != NULL) {
    set_has_bytes();
    value_.bytes_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
        bytes);
  }
  // @@protoc_insertion_point(field_set_allocated:Octo.GenericValue.bytes)
}

// optional int32 int32 = 3;
inline bool GenericValue::has_int32() const {
  return value_case() == kInt32;
}
inline void GenericValue::set_has_int32() {
  _oneof_case_[0] = kInt32;
}
inline void GenericValue::clear_int32() {
  if (has_int32()) {
    value_.int32_ = 0;
    clear_has_value();
  }
}
inline ::google::protobuf::int32 GenericValue::int32() const {
  // @@protoc_insertion_point(field_get:Octo.GenericValue.int32)
  if (has_int32()) {
    return value_.int32_;
  }
  return 0;
}
inline void GenericValue::set_int32(::google::protobuf::int32 value) {
  if (!has_int32()) {
    clear_value();
    set_has_int32();
  }
  value_.int32_ = value;
  // @@protoc_insertion_point(field_set:Octo.GenericValue.int32)
}

// optional int64 int64 = 5;
inline bool GenericValue::has_int64() const {
  return value_case() == kInt64;
}
inline void GenericValue::set_has_int64() {
  _oneof_case_[0] = kInt64;
}
inline void GenericValue::clear_int64() {
  if (has_int64()) {
    value_.int64_ = GOOGLE_LONGLONG(0);
    clear_has_value();
  }
}
inline ::google::protobuf::int64 GenericValue::int64() const {
  // @@protoc_insertion_point(field_get:Octo.GenericValue.int64)
  if (has_int64()) {
    return value_.int64_;
  }
  return GOOGLE_LONGLONG(0);
}
inline void GenericValue::set_int64(::google::protobuf::int64 value) {
  if (!has_int64()) {
    clear_value();
    set_has_int64();
  }
  value_.int64_ = value;
  // @@protoc_insertion_point(field_set:Octo.GenericValue.int64)
}

// optional bool boolean = 7;
inline bool GenericValue::has_boolean() const {
  return value_case() == kBoolean;
}
inline void GenericValue::set_has_boolean() {
  _oneof_case_[0] = kBoolean;
}
inline void GenericValue::clear_boolean() {
  if (has_boolean()) {
    value_.boolean_ = false;
    clear_has_value();
  }
}
inline bool GenericValue::boolean() const {
  // @@protoc_insertion_point(field_get:Octo.GenericValue.boolean)
  if (has_boolean()) {
    return value_.boolean_;
  }
  return false;
}
inline void GenericValue::set_boolean(bool value) {
  if (!has_boolean()) {
    clear_value();
    set_has_boolean();
  }
  value_.boolean_ = value;
  // @@protoc_insertion_point(field_set:Octo.GenericValue.boolean)
}

// optional double real = 8;
inline bool GenericValue::has_real() const {
  return value_case() == kReal;
}
inline void GenericValue::set_has_real() {
  _oneof_case_[0] = kReal;
}
inline void GenericValue::clear_real() {
  if (has_real()) {
    value_.real_ = 0;
    clear_has_value();
  }
}
inline double GenericValue::real() const {
  // @@protoc_insertion_point(field_get:Octo.GenericValue.real)
  if (has_real()) {
    return value_.real_;
  }
  return 0;
}
inline void GenericValue::set_real(double value) {
  if (!has_real()) {
    clear_value();
    set_has_real();
  }
  value_.real_ = value;
  // @@protoc_insertion_point(field_set:Octo.GenericValue.real)
}

// optional .Octo.MapValue map = 10;
inline bool GenericValue::has_map() const {
  return value_case() == kMap;
}
inline void GenericValue::set_has_map() {
  _oneof_case_[0] = kMap;
}
inline void GenericValue::clear_map() {
  if (has_map()) {
    delete value_.map_;
    clear_has_value();
  }
}
inline  const ::Octo::MapValue& GenericValue::map() const {
  // @@protoc_insertion_point(field_get:Octo.GenericValue.map)
  return has_map()
      ? *value_.map_
      : ::Octo::MapValue::default_instance();
}
inline ::Octo::MapValue* GenericValue::mutable_map() {
  if (!has_map()) {
    clear_value();
    set_has_map();
    value_.map_ = new ::Octo::MapValue;
  }
  // @@protoc_insertion_point(field_mutable:Octo.GenericValue.map)
  return value_.map_;
}
inline ::Octo::MapValue* GenericValue::release_map() {
  if (has_map()) {
    clear_has_value();
    ::Octo::MapValue* temp = value_.map_;
    value_.map_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline void GenericValue::set_allocated_map(::Octo::MapValue* map) {
  clear_value();
  if (map) {
    set_has_map();
    value_.map_ = map;
  }
  // @@protoc_insertion_point(field_set_allocated:Octo.GenericValue.map)
}

// optional .Octo.SMapValue str_map = 11;
inline bool GenericValue::has_str_map() const {
  return value_case() == kStrMap;
}
inline void GenericValue::set_has_str_map() {
  _oneof_case_[0] = kStrMap;
}
inline void GenericValue::clear_str_map() {
  if (has_str_map()) {
    delete value_.str_map_;
    clear_has_value();
  }
}
inline  const ::Octo::SMapValue& GenericValue::str_map() const {
  // @@protoc_insertion_point(field_get:Octo.GenericValue.str_map)
  return has_str_map()
      ? *value_.str_map_
      : ::Octo::SMapValue::default_instance();
}
inline ::Octo::SMapValue* GenericValue::mutable_str_map() {
  if (!has_str_map()) {
    clear_value();
    set_has_str_map();
    value_.str_map_ = new ::Octo::SMapValue;
  }
  // @@protoc_insertion_point(field_mutable:Octo.GenericValue.str_map)
  return value_.str_map_;
}
inline ::Octo::SMapValue* GenericValue::release_str_map() {
  if (has_str_map()) {
    clear_has_value();
    ::Octo::SMapValue* temp = value_.str_map_;
    value_.str_map_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline void GenericValue::set_allocated_str_map(::Octo::SMapValue* str_map) {
  clear_value();
  if (str_map) {
    set_has_str_map();
    value_.str_map_ = str_map;
  }
  // @@protoc_insertion_point(field_set_allocated:Octo.GenericValue.str_map)
}

// optional .Octo.ListValue list = 12;
inline bool GenericValue::has_list() const {
  return value_case() == kList;
}
inline void GenericValue::set_has_list() {
  _oneof_case_[0] = kList;
}
inline void GenericValue::clear_list() {
  if (has_list()) {
    delete value_.list_;
    clear_has_value();
  }
}
inline  const ::Octo::ListValue& GenericValue::list() const {
  // @@protoc_insertion_point(field_get:Octo.GenericValue.list)
  return has_list()
      ? *value_.list_
      : ::Octo::ListValue::default_instance();
}
inline ::Octo::ListValue* GenericValue::mutable_list() {
  if (!has_list()) {
    clear_value();
    set_has_list();
    value_.list_ = new ::Octo::ListValue;
  }
  // @@protoc_insertion_point(field_mutable:Octo.GenericValue.list)
  return value_.list_;
}
inline ::Octo::ListValue* GenericValue::release_list() {
  if (has_list()) {
    clear_has_value();
    ::Octo::ListValue* temp = value_.list_;
    value_.list_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline void GenericValue::set_allocated_list(::Octo::ListValue* list) {
  clear_value();
  if (list) {
    set_has_list();
    value_.list_ = list;
  }
  // @@protoc_insertion_point(field_set_allocated:Octo.GenericValue.list)
}

// optional .Octo.Int64ListValue int_list = 13;
inline bool GenericValue::has_int_list() const {
  return value_case() == kIntList;
}
inline void GenericValue::set_has_int_list() {
  _oneof_case_[0] = kIntList;
}
inline void GenericValue::clear_int_list() {
  if (has_int_list()) {
    delete value_.int_list_;
    clear_has_value();
  }
}
inline  const ::Octo::Int64ListValue& GenericValue::int_list() const {
  // @@protoc_insertion_point(field_get:Octo.GenericValue.int_list)
  return has_int_list()
      ? *value_.int_list_
      : ::Octo::Int64ListValue::default_instance();
}
inline ::Octo::Int64ListValue* GenericValue::mutable_int_list() {
  if (!has_int_list()) {
    clear_value();
    set_has_int_list();
    value_.int_list_ = new ::Octo::Int64ListValue;
  }
  // @@protoc_insertion_point(field_mutable:Octo.GenericValue.int_list)
  return value_.int_list_;
}
inline ::Octo::Int64ListValue* GenericValue::release_int_list() {
  if (has_int_list()) {
    clear_has_value();
    ::Octo::Int64ListValue* temp = value_.int_list_;
    value_.int_list_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline void GenericValue::set_allocated_int_list(::Octo::Int64ListValue* int_list) {
  clear_value();
  if (int_list) {
    set_has_int_list();
    value_.int_list_ = int_list;
  }
  // @@protoc_insertion_point(field_set_allocated:Octo.GenericValue.int_list)
}

// optional .Octo.StringListValue str_list = 14;
inline bool GenericValue::has_str_list() const {
  return value_case() == kStrList;
}
inline void GenericValue::set_has_str_list() {
  _oneof_case_[0] = kStrList;
}
inline void GenericValue::clear_str_list() {
  if (has_str_list()) {
    delete value_.str_list_;
    clear_has_value();
  }
}
inline  const ::Octo::StringListValue& GenericValue::str_list() const {
  // @@protoc_insertion_point(field_get:Octo.GenericValue.str_list)
  return has_str_list()
      ? *value_.str_list_
      : ::Octo::StringListValue::default_instance();
}
inline ::Octo::StringListValue* GenericValue::mutable_str_list() {
  if (!has_str_list()) {
    clear_value();
    set_has_str_list();
    value_.str_list_ = new ::Octo::StringListValue;
  }
  // @@protoc_insertion_point(field_mutable:Octo.GenericValue.str_list)
  return value_.str_list_;
}
inline ::Octo::StringListValue* GenericValue::release_str_list() {
  if (has_str_list()) {
    clear_has_value();
    ::Octo::StringListValue* temp = value_.str_list_;
    value_.str_list_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline void GenericValue::set_allocated_str_list(::Octo::StringListValue* str_list) {
  clear_value();
  if (str_list) {
    set_has_str_list();
    value_.str_list_ = str_list;
  }
  // @@protoc_insertion_point(field_set_allocated:Octo.GenericValue.str_list)
}

inline bool GenericValue::has_value() const {
  return value_case() != VALUE_NOT_SET;
}
inline void GenericValue::clear_has_value() {
  _oneof_case_[0] = VALUE_NOT_SET;
}
inline GenericValue::ValueCase GenericValue::value_case() const {
  return GenericValue::ValueCase(_oneof_case_[0]);
}
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Octo

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_GenericValue_2eproto__INCLUDED
